package com.nst.GUI;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class EconomyStatistic extends javax.swing.JFrame {

    /**
     * Creates new form EconomyStatistic
     */
    public EconomyStatistic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OkStatisticButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BeginDay = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        BeginMonth = new javax.swing.JComboBox<>();
        BeginYear = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EndDay = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        EndMonth = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        EndYear = new javax.swing.JComboBox<>();
        BackToSearchMenuButton = new javax.swing.JButton();
        BackToHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thống kê doanh thu");

        jLabel3.setText("Ngày bắt đầu kết toán");

        OkStatisticButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OkStatisticButton.setText("OK");
        OkStatisticButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkStatisticButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thuốc", "Tên thuốc", "Giá nhập", "Giá bán", "Số lượng bán", "Lãi"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel4.setText("Ngày kết thúc kết toán");

        jLabel2.setText("Ngày");

        BeginDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", " " }));
        BeginDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeginDayActionPerformed(evt);
            }
        });

        jLabel5.setText("Tháng");

        BeginMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        BeginYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        jLabel6.setText("Năm");

        jLabel7.setText("Ngày");

        EndDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", " " }));
        EndDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndDayActionPerformed(evt);
            }
        });

        jLabel8.setText("Tháng");

        EndMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel9.setText("Năm");

        EndYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        BackToSearchMenuButton.setBackground(new java.awt.Color(255, 51, 0));
        BackToSearchMenuButton.setForeground(new java.awt.Color(51, 51, 51));
        BackToSearchMenuButton.setText("Back");
        BackToSearchMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToSearchMenuButtonActionPerformed(evt);
            }
        });

        BackToHome.setBackground(new java.awt.Color(102, 255, 102));
        BackToHome.setForeground(new java.awt.Color(51, 51, 51));
        BackToHome.setText("Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BeginDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EndDay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BeginMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(OkStatisticButton))
                            .addComponent(BeginYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackToSearchMenuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BackToHome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackToSearchMenuButton)
                    .addComponent(BackToHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BeginDay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BeginMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BeginYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OkStatisticButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndDay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private boolean TimeChecker1(int day,int month,int year)             //kiểm tra xem thời gian nhập vào đã đúng định dạng chưa
    {
        boolean check = true;
        if(year % 4 ==0)
        {
            if(month == 2)
            {
                if(day >29) check=false;
            }
            else if(month == 4 || month == 6 || month == 9 || month == 11)
            {
                if(day>30) check = false;
            }
        }
        else
        {
           if(month == 2)
            {
                if(day >28) check=false;
            }
            else if(month == 4 || month == 6 || month == 9 || month == 11)
            {
                if(day>30) check = false;
            }           
        }
        return check;
    }
    private boolean TimeChecker2(int beginDay,int beginMonth,int beginYear,int endDay,int endMonth,int endYear)
    {           // kiểm tra xem thời gian bắt đầu có nhỏ hơn kết thúc không
        boolean check = true;
        if(beginYear> endYear)
        {
            check= false;
        }
        if(beginYear == endYear)
        {
            if(beginMonth>endMonth)
            {
                check= false;
            }
            if(beginMonth == endMonth)
            {
                if(beginDay> endDay)
                {
                    check= false;
                }
            }
        }
        return check;
    }
    private void OkStatisticButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkStatisticButtonActionPerformed
//        try {
//            // TODO add your handling code here
//            String beginDay= BeginDay.getSelectedItem().toString();
//            String beginMonth=BeginMonth.getSelectedItem().toString();
//            String beginYear=BeginYear.getSelectedItem().toString();
//            String endDay=EndDay.getSelectedItem().toString();
//            String endMonth=EndMonth.getSelectedItem().toString();
//            String endYear=EndYear.getSelectedItem().toString();
//            boolean check1= TimeChecker1(Integer.parseInt(beginDay),Integer.parseInt(beginMonth),Integer.parseInt(beginYear));
//            boolean check2= TimeChecker1(Integer.parseInt(endDay),Integer.parseInt(endMonth),Integer.parseInt(endYear));
//            boolean check3= TimeChecker2(Integer.parseInt(beginDay), Integer.parseInt(beginMonth), Integer.parseInt(beginYear)
//                    , Integer.parseInt(endDay), Integer.parseInt(endMonth), Integer.parseInt(endYear));
//            if(check1 ==false || check2==false || check3==false)
//            {
//                new TimeWrongNotification(1).setVisible(true);
//            }
//            
//            Date beginTime = new SimpleDateFormat("dd-MM-yyyy").parse(beginDay+"-"+beginMonth+"-"+beginYear);
//            Date endTime = new SimpleDateFormat("dd-MM-yyyy").parse(endDay+"-"+endMonth+"-"+endYear);
//            Object[][] listOfMedicine = thuocHelper.Statistic(beginTime,endTime);      // gọi hàm Statistic thống kê trong một khoảng thời gian
//            DefaultTableModel Model = new DefaultTableModel()
//            {
//                @Override
//                public boolean isCellEditable(int row,int column)
//                {
//                    return false;
//                }
//            };
//            jTable1.setModel(Model);
//            Model=(DefaultTableModel)jTable1.getModel();
//            int n= listOfMedicine.size();
//            double Sum=0;
//            for(int i=0;i<n;i++)
//            {
//                thuoc Medicine = listOfMedicine.get(i);
//                String id= Medicine.getCode();
//                String name= Medicine.getName();
//                double pricein= Medicine.getPriceIn();
//                double priceout= Medicine.getPriceIn()*Medicine.getCoeff();
//                double numberOut= Medicine.getNumberOut();
//                double profit= Medicine.getCoeff()*Medicine.getNumberOut();
//                Sum+=profit;
//                Model.addRow(new Object[]
//                {
//                    name,pricein,priceout,numberOut,profit
//                }
//                );
//            }
//            SumLabel.setText("Tổng doanh thu: "+String.valueOf(Sum));
//        } catch (ParseException ex) {
//            Logger.getLogger(EconomyStatistic.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_OkStatisticButtonActionPerformed

    private void BeginDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeginDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BeginDayActionPerformed

    private void EndDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndDayActionPerformed

    private void BackToSearchMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToSearchMenuButtonActionPerformed
        new SearchMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackToSearchMenuButtonActionPerformed

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackToHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EconomyStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EconomyStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EconomyStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EconomyStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EconomyStatistic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHome;
    private javax.swing.JButton BackToSearchMenuButton;
    private javax.swing.JComboBox<String> BeginDay;
    private javax.swing.JComboBox<String> BeginMonth;
    private javax.swing.JComboBox<String> BeginYear;
    private javax.swing.JComboBox<String> EndDay;
    private javax.swing.JComboBox<String> EndMonth;
    private javax.swing.JComboBox<String> EndYear;
    private javax.swing.JButton OkStatisticButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
