/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nst.GUI;

/**
 *
 * @author admin
 */
public class Notification extends javax.swing.JFrame {

    /**
     * Creates new form TimeWrongNotification
     */
    public Notification(int i) {
        initComponents();
        RemoveAllNotifications();
        SelectNotification(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLocation(new java.awt.Point(700, 250));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Time's format is not correct!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 110, 315, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel2.setText("You have not permisson for this function! Try another one");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 130, 482, 44);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveAllNotifications()
    {
        this.removeAll();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void SelectNotification(int i) {
        switch(i)
        {
            case 1:
            {
                add(jLabel1);
                break;
            }
            case 2:
            {
                add(jLabel2);
                break;
            }
        }
    }
}
